export interface FoodDatabaseItem {
  id: string;
  name: string;
  category: string;
  servingSize: number;
  servingUnit: string;
  calories: number;
  sugar: number;
  protein: number;
  carbs: number;
  fat: number;
  commonPortions: Array<{
    name: string;
    size: number;
  }>;
}

export const foodDatabase: FoodDatabaseItem[] = [
  // Fruits
  {
    id: 'apple',
    name: 'Apple',
    category: 'Fruits',
    servingSize: 100,
    servingUnit: 'g',
    calories: 52,
    sugar: 10.4,
    protein: 0.3,
    carbs: 14,
    fat: 0.2,
    commonPortions: [
      { name: '1 medium', size: 182 },
      { name: '1 small', size: 149 },
      { name: '1 cup sliced', size: 109 },
    ],
  },
  {
    id: 'banana',
    name: 'Banana',
    category: 'Fruits',
    servingSize: 100,
    servingUnit: 'g',
    calories: 89,
    sugar: 12.2,
    protein: 1.1,
    carbs: 23,
    fat: 0.3,
    commonPortions: [
      { name: '1 medium', size: 118 },
      { name: '1 small', size: 101 },
      { name: '1 cup sliced', size: 150 },
    ],
  },
  {
    id: 'orange',
    name: 'Orange',
    category: 'Fruits',
    servingSize: 100,
    servingUnit: 'g',
    calories: 47,
    sugar: 9.4,
    protein: 0.9,
    carbs: 12,
    fat: 0.1,
    commonPortions: [
      { name: '1 medium', size: 131 },
      { name: '1 small', size: 96 },
    ],
  },
  {
    id: 'grapes',
    name: 'Grapes',
    category: 'Fruits',
    servingSize: 100,
    servingUnit: 'g',
    calories: 69,
    sugar: 15.5,
    protein: 0.7,
    carbs: 18,
    fat: 0.2,
    commonPortions: [
      { name: '1 cup', size: 151 },
      { name: '1 bunch', size: 250 },
    ],
  },
  {
    id: 'strawberries',
    name: 'Strawberries',
    category: 'Fruits',
    servingSize: 100,
    servingUnit: 'g',
    calories: 32,
    sugar: 4.9,
    protein: 0.7,
    carbs: 7.7,
    fat: 0.3,
    commonPortions: [
      { name: '1 cup whole', size: 152 },
      { name: '1 cup sliced', size: 166 },
    ],
  },
  {
    id: 'blueberries',
    name: 'Blueberries',
    category: 'Fruits',
    servingSize: 100,
    servingUnit: 'g',
    calories: 57,
    sugar: 10,
    protein: 0.7,
    carbs: 14,
    fat: 0.3,
    commonPortions: [
      { name: '1 cup', size: 148 },
    ],
  },
  {
    id: 'watermelon',
    name: 'Watermelon',
    category: 'Fruits',
    servingSize: 100,
    servingUnit: 'g',
    calories: 30,
    sugar: 6.2,
    protein: 0.6,
    carbs: 8,
    fat: 0.2,
    commonPortions: [
      { name: '1 cup diced', size: 152 },
      { name: '1 wedge', size: 286 },
    ],
  },

  // Vegetables
  {
    id: 'broccoli',
    name: 'Broccoli',
    category: 'Vegetables',
    servingSize: 100,
    servingUnit: 'g',
    calories: 34,
    sugar: 1.7,
    protein: 2.8,
    carbs: 7,
    fat: 0.4,
    commonPortions: [
      { name: '1 cup chopped', size: 91 },
      { name: '1 stalk', size: 151 },
    ],
  },
  {
    id: 'carrot',
    name: 'Carrot',
    category: 'Vegetables',
    servingSize: 100,
    servingUnit: 'g',
    calories: 41,
    sugar: 4.7,
    protein: 0.9,
    carbs: 10,
    fat: 0.2,
    commonPortions: [
      { name: '1 medium', size: 61 },
      { name: '1 cup chopped', size: 128 },
    ],
  },
  {
    id: 'spinach',
    name: 'Spinach',
    category: 'Vegetables',
    servingSize: 100,
    servingUnit: 'g',
    calories: 23,
    sugar: 0.4,
    protein: 2.9,
    carbs: 3.6,
    fat: 0.4,
    commonPortions: [
      { name: '1 cup raw', size: 30 },
      { name: '1 cup cooked', size: 180 },
    ],
  },
  {
    id: 'tomato',
    name: 'Tomato',
    category: 'Vegetables',
    servingSize: 100,
    servingUnit: 'g',
    calories: 18,
    sugar: 2.6,
    protein: 0.9,
    carbs: 3.9,
    fat: 0.2,
    commonPortions: [
      { name: '1 medium', size: 123 },
      { name: '1 cup chopped', size: 180 },
    ],
  },
  {
    id: 'potato',
    name: 'Potato',
    category: 'Vegetables',
    servingSize: 100,
    servingUnit: 'g',
    calories: 77,
    sugar: 0.8,
    protein: 2,
    carbs: 17,
    fat: 0.1,
    commonPortions: [
      { name: '1 medium', size: 213 },
      { name: '1 cup diced', size: 132 },
    ],
  },

  // Proteins
  {
    id: 'chicken-breast',
    name: 'Chicken Breast',
    category: 'Proteins',
    servingSize: 100,
    servingUnit: 'g',
    calories: 165,
    sugar: 0,
    protein: 31,
    carbs: 0,
    fat: 3.6,
    commonPortions: [
      { name: '1 breast', size: 172 },
      { name: '1 cup diced', size: 140 },
    ],
  },
  {
    id: 'salmon',
    name: 'Salmon',
    category: 'Proteins',
    servingSize: 100,
    servingUnit: 'g',
    calories: 208,
    sugar: 0,
    protein: 20,
    carbs: 0,
    fat: 13,
    commonPortions: [
      { name: '1 fillet (half)', size: 178 },
      { name: '1 cup cooked', size: 154 },
    ],
  },
  {
    id: 'egg',
    name: 'Egg',
    category: 'Proteins',
    servingSize: 100,
    servingUnit: 'g',
    calories: 155,
    sugar: 1.1,
    protein: 13,
    carbs: 1.1,
    fat: 11,
    commonPortions: [
      { name: '1 large', size: 50 },
      { name: '1 extra large', size: 56 },
    ],
  },
  {
    id: 'beef-ground',
    name: 'Ground Beef (85%)',
    category: 'Proteins',
    servingSize: 100,
    servingUnit: 'g',
    calories: 250,
    sugar: 0,
    protein: 26,
    carbs: 0,
    fat: 17,
    commonPortions: [
      { name: '1 patty', size: 113 },
      { name: '1 cup cooked', size: 226 },
    ],
  },
  {
    id: 'tofu',
    name: 'Tofu',
    category: 'Proteins',
    servingSize: 100,
    servingUnit: 'g',
    calories: 76,
    sugar: 0.9,
    protein: 8,
    carbs: 1.9,
    fat: 4.8,
    commonPortions: [
      { name: '1 cup cubed', size: 126 },
    ],
  },

  // Grains & Starches
  {
    id: 'rice-white',
    name: 'White Rice (cooked)',
    category: 'Grains & Starches',
    servingSize: 100,
    servingUnit: 'g',
    calories: 130,
    sugar: 0.1,
    protein: 2.7,
    carbs: 28,
    fat: 0.3,
    commonPortions: [
      { name: '1 cup', size: 158 },
      { name: '1 bowl', size: 200 },
    ],
  },
  {
    id: 'rice-brown',
    name: 'Brown Rice (cooked)',
    category: 'Grains & Starches',
    servingSize: 100,
    servingUnit: 'g',
    calories: 112,
    sugar: 0.4,
    protein: 2.6,
    carbs: 24,
    fat: 0.9,
    commonPortions: [
      { name: '1 cup', size: 195 },
      { name: '1 bowl', size: 200 },
    ],
  },
  {
    id: 'bread-white',
    name: 'White Bread',
    category: 'Grains & Starches',
    servingSize: 100,
    servingUnit: 'g',
    calories: 265,
    sugar: 5,
    protein: 9,
    carbs: 49,
    fat: 3.2,
    commonPortions: [
      { name: '1 slice', size: 25 },
      { name: '2 slices', size: 50 },
    ],
  },
  {
    id: 'bread-whole',
    name: 'Whole Wheat Bread',
    category: 'Grains & Starches',
    servingSize: 100,
    servingUnit: 'g',
    calories: 247,
    sugar: 5.5,
    protein: 13,
    carbs: 41,
    fat: 3.4,
    commonPortions: [
      { name: '1 slice', size: 28 },
      { name: '2 slices', size: 56 },
    ],
  },
  {
    id: 'pasta',
    name: 'Pasta (cooked)',
    category: 'Grains & Starches',
    servingSize: 100,
    servingUnit: 'g',
    calories: 131,
    sugar: 1.3,
    protein: 5,
    carbs: 25,
    fat: 1.1,
    commonPortions: [
      { name: '1 cup', size: 140 },
      { name: '1 bowl', size: 220 },
    ],
  },
  {
    id: 'oatmeal',
    name: 'Oatmeal (cooked)',
    category: 'Grains & Starches',
    servingSize: 100,
    servingUnit: 'g',
    calories: 71,
    sugar: 0.6,
    protein: 2.5,
    carbs: 12,
    fat: 1.4,
    commonPortions: [
      { name: '1 cup', size: 234 },
      { name: '1 bowl', size: 250 },
    ],
  },

  // Dairy
  {
    id: 'milk-whole',
    name: 'Whole Milk',
    category: 'Dairy',
    servingSize: 100,
    servingUnit: 'ml',
    calories: 61,
    sugar: 5,
    protein: 3.2,
    carbs: 4.8,
    fat: 3.3,
    commonPortions: [
      { name: '1 cup', size: 244 },
      { name: '1 glass', size: 300 },
    ],
  },
  {
    id: 'milk-skim',
    name: 'Skim Milk',
    category: 'Dairy',
    servingSize: 100,
    servingUnit: 'ml',
    calories: 34,
    sugar: 5,
    protein: 3.4,
    carbs: 5,
    fat: 0.1,
    commonPortions: [
      { name: '1 cup', size: 244 },
      { name: '1 glass', size: 300 },
    ],
  },
  {
    id: 'yogurt-greek',
    name: 'Greek Yogurt',
    category: 'Dairy',
    servingSize: 100,
    servingUnit: 'g',
    calories: 59,
    sugar: 3.6,
    protein: 10,
    carbs: 3.6,
    fat: 0.4,
    commonPortions: [
      { name: '1 cup', size: 245 },
      { name: '1 container', size: 170 },
    ],
  },
  {
    id: 'cheese-cheddar',
    name: 'Cheddar Cheese',
    category: 'Dairy',
    servingSize: 100,
    servingUnit: 'g',
    calories: 403,
    sugar: 0.5,
    protein: 25,
    carbs: 1.3,
    fat: 33,
    commonPortions: [
      { name: '1 oz', size: 28 },
      { name: '1 cup shredded', size: 113 },
    ],
  },

  // Snacks & Sweets
  {
    id: 'almonds',
    name: 'Almonds',
    category: 'Snacks & Sweets',
    servingSize: 100,
    servingUnit: 'g',
    calories: 579,
    sugar: 4,
    protein: 21,
    carbs: 22,
    fat: 50,
    commonPortions: [
      { name: '1 handful', size: 23 },
      { name: '1/4 cup', size: 30 },
    ],
  },
  {
    id: 'peanut-butter',
    name: 'Peanut Butter',
    category: 'Snacks & Sweets',
    servingSize: 100,
    servingUnit: 'g',
    calories: 588,
    sugar: 9,
    protein: 25,
    carbs: 20,
    fat: 50,
    commonPortions: [
      { name: '1 tbsp', size: 16 },
      { name: '2 tbsp', size: 32 },
    ],
  },
  {
    id: 'dark-chocolate',
    name: 'Dark Chocolate (70%)',
    category: 'Snacks & Sweets',
    servingSize: 100,
    servingUnit: 'g',
    calories: 598,
    sugar: 24,
    protein: 7.8,
    carbs: 46,
    fat: 43,
    commonPortions: [
      { name: '1 square', size: 10 },
      { name: '1 bar', size: 40 },
    ],
  },
  {
    id: 'chips-potato',
    name: 'Potato Chips',
    category: 'Snacks & Sweets',
    servingSize: 100,
    servingUnit: 'g',
    calories: 536,
    sugar: 0.4,
    protein: 7,
    carbs: 53,
    fat: 35,
    commonPortions: [
      { name: '1 small bag', size: 28 },
      { name: '1 handful', size: 20 },
    ],
  },
  {
    id: 'cookie-chocolate-chip',
    name: 'Chocolate Chip Cookie',
    category: 'Snacks & Sweets',
    servingSize: 100,
    servingUnit: 'g',
    calories: 480,
    sugar: 32,
    protein: 5,
    carbs: 62,
    fat: 24,
    commonPortions: [
      { name: '1 cookie (medium)', size: 25 },
      { name: '1 cookie (large)', size: 40 },
      { name: '2 cookies', size: 50 },
    ],
  },
  {
    id: 'cookie-oatmeal',
    name: 'Oatmeal Cookie',
    category: 'Snacks & Sweets',
    servingSize: 100,
    servingUnit: 'g',
    calories: 450,
    sugar: 28,
    protein: 6,
    carbs: 65,
    fat: 18,
    commonPortions: [
      { name: '1 cookie', size: 30 },
      { name: '2 cookies', size: 60 },
    ],
  },
  {
    id: 'cookie-fortune',
    name: 'Fortune Cookie',
    category: 'Snacks & Sweets',
    servingSize: 100,
    servingUnit: 'g',
    calories: 410,
    sugar: 18,
    protein: 5,
    carbs: 58,
    fat: 18,
    commonPortions: [
      { name: '1 cookie', size: 10 },
      { name: '2 cookies', size: 20 },
    ],
  },
  {
    id: 'donut- glazed',
    name: 'Glazed Donut',
    category: 'Snacks & Sweets',
    servingSize: 100,
    servingUnit: 'g',
    calories: 409,
    sugar: 24,
    protein: 5,
    carbs: 51,
    fat: 21,
    commonPortions: [
      { name: '1 donut', size: 45 },
      { name: '1 donut (large)', size: 65 },
    ],
  },
  {
    id: 'donut-chocolate',
    name: 'Chocolate Donut',
    category: 'Snacks & Sweets',
    servingSize: 100,
    servingUnit: 'g',
    calories: 417,
    sugar: 28,
    protein: 5,
    carbs: 52,
    fat: 22,
    commonPortions: [
      { name: '1 donut', size: 45 },
      { name: '1 donut (large)', size: 65 },
    ],
  },
  {
    id: 'popcorn',
    name: 'Popcorn (air-popped)',
    category: 'Snacks & Sweets',
    servingSize: 100,
    servingUnit: 'g',
    calories: 387,
    sugar: 0.9,
    protein: 13,
    carbs: 78,
    fat: 4,
    commonPortions: [
      { name: '1 cup', size: 8 },
      { name: '1 small bowl', size: 30 },
    ],
  },
  {
    id: 'granola-bar',
    name: 'Granola Bar',
    category: 'Snacks & Sweets',
    servingSize: 100,
    servingUnit: 'g',
    calories: 471,
    sugar: 21,
    protein: 9,
    carbs: 64,
    fat: 19,
    commonPortions: [
      { name: '1 bar', size: 24 },
      { name: '1 bar (large)', size: 35 },
    ],
  },
  {
    id: 'crackers',
    name: 'Saltine Crackers',
    category: 'Snacks & Sweets',
    servingSize: 100,
    servingUnit: 'g',
    calories: 421,
    sugar: 3,
    protein: 9,
    carbs: 74,
    fat: 8,
    commonPortions: [
      { name: '5 crackers', size: 25 },
      { name: '1 sleeve', size: 50 },
    ],
  },
  {
    id: 'pretzels',
    name: 'Pretzels',
    category: 'Snacks & Sweets',
    servingSize: 100,
    servingUnit: 'g',
    calories: 368,
    sugar: 2,
    protein: 9,
    carbs: 78,
    fat: 3,
    commonPortions: [
      { name: '1 handful', size: 20 },
      { name: '1 small bag', size: 50 },
    ],
  },
  {
    id: 'candy-bar-snickers',
    name: 'Snickers Bar',
    category: 'Snacks & Sweets',
    servingSize: 100,
    servingUnit: 'g',
    calories: 488,
    sugar: 48,
    protein: 7,
    carbs: 61,
    fat: 25,
    commonPortions: [
      { name: '1 bar (regular)', size: 52 },
      { name: '1 fun size', size: 18 },
    ],
  },
  {
    id: 'candy-bar-milkyway',
    name: 'Milky Way Bar',
    category: 'Snacks & Sweets',
    servingSize: 100,
    servingUnit: 'g',
    calories: 458,
    sugar: 55,
    protein: 4,
    carbs: 70,
    fat: 18,
    commonPortions: [
      { name: '1 bar (regular)', size: 58 },
      { name: '1 fun size', size: 18 },
    ],
  },
  {
    id: 'candy-bar-twix',
    name: 'Twix Bar',
    category: 'Snacks & Sweets',
    servingSize: 100,
    servingUnit: 'g',
    calories: 503,
    sugar: 46,
    protein: 4,
    carbs: 64,
    fat: 26,
    commonPortions: [
      { name: '1 bar (2 sticks)', size: 50 },
      { name: '1 stick', size: 25 },
    ],
  },
  {
    id: 'mms-regular',
    name: "M&M's (regular)",
    category: 'Snacks & Sweets',
    servingSize: 100,
    servingUnit: 'g',
    calories: 485,
    sugar: 58,
    protein: 4,
    carbs: 68,
    fat: 22,
    commonPortions: [
      { name: '1 fun size', size: 20 },
      { name: '1 small bag', size: 40 },
    ],
  },
  {
    id: 'gummy-bears',
    name: 'Gummy Bears',
    category: 'Snacks & Sweets',
    servingSize: 100,
    servingUnit: 'g',
    calories: 340,
    sugar: 44,
    protein: 5,
    carbs: 76,
    fat: 0,
    commonPortions: [
      { name: '1 handful', size: 20 },
      { name: '1 small pack', size: 50 },
    ],
  },
  {
    id: 'licorice',
    name: 'Red Licorice',
    category: 'Snacks & Sweets',
    servingSize: 100,
    servingUnit: 'g',
    calories: 360,
    sugar: 50,
    protein: 2,
    carbs: 82,
    fat: 0,
    commonPortions: [
      { name: '1 piece', size: 15 },
      { name: '1 small bag', size: 50 },
    ],
  },
  {
    id: 'jelly-beans',
    name: 'Jelly Beans',
    category: 'Snacks & Sweets',
    servingSize: 100,
    servingUnit: 'g',
    calories: 375,
    sugar: 67,
    protein: 0,
    carbs: 94,
    fat: 0,
    commonPortions: [
      { name: '1 handful', size: 25 },
      { name: '1 small bag', size: 50 },
    ],
  },
  {
    id: 'candy-corn',
    name: 'Candy Corn',
    category: 'Snacks & Sweets',
    servingSize: 100,
    servingUnit: 'g',
    calories: 375,
    sugar: 75,
    protein: 0,
    carbs: 94,
    fat: 0,
    commonPortions: [
      { name: '1 handful', size: 25 },
      { name: '1 small bag', size: 50 },
    ],
  },

  // Ice Cream & Frozen Desserts
  {
    id: 'ice-cream-vanilla',
    name: 'Vanilla Ice Cream',
    category: 'Ice Cream & Frozen',
    servingSize: 100,
    servingUnit: 'g',
    calories: 207,
    sugar: 21,
    protein: 3.5,
    carbs: 24,
    fat: 11,
    commonPortions: [
      { name: '1 scoop', size: 66 },
      { name: '1/2 cup', size: 72 },
      { name: '1 cup', size: 144 },
    ],
  },
  {
    id: 'ice-cream-chocolate',
    name: 'Chocolate Ice Cream',
    category: 'Ice Cream & Frozen',
    servingSize: 100,
    servingUnit: 'g',
    calories: 216,
    sugar: 22,
    protein: 3.8,
    carbs: 26,
    fat: 11,
    commonPortions: [
      { name: '1 scoop', size: 66 },
      { name: '1/2 cup', size: 72 },
      { name: '1 cup', size: 144 },
    ],
  },
  {
    id: 'ice-cream-strawberry',
    name: 'Strawberry Ice Cream',
    category: 'Ice Cream & Frozen',
    servingSize: 100,
    servingUnit: 'g',
    calories: 192,
    sugar: 22,
    protein: 3.2,
    carbs: 25,
    fat: 9,
    commonPortions: [
      { name: '1 scoop', size: 66 },
      { name: '1/2 cup', size: 72 },
      { name: '1 cup', size: 144 },
    ],
  },
  {
    id: 'ice-cream-mint-chip',
    name: 'Mint Chocolate Chip Ice Cream',
    category: 'Ice Cream & Frozen',
    servingSize: 100,
    servingUnit: 'g',
    calories: 220,
    sugar: 21,
    protein: 3.5,
    carbs: 27,
    fat: 12,
    commonPortions: [
      { name: '1 scoop', size: 66 },
      { name: '1/2 cup', size: 72 },
    ],
  },
  {
    id: 'ice-cream-cookies-cream',
    name: 'Cookies and Cream Ice Cream',
    category: 'Ice Cream & Frozen',
    servingSize: 100,
    servingUnit: 'g',
    calories: 240,
    sugar: 23,
    protein: 3.5,
    carbs: 30,
    fat: 13,
    commonPortions: [
      { name: '1 scoop', size: 66 },
      { name: '1/2 cup', size: 72 },
    ],
  },
  {
    id: 'ice-cream-rocky-road',
    name: 'Rocky Road Ice Cream',
    category: 'Ice Cream & Frozen',
    servingSize: 100,
    servingUnit: 'g',
    calories: 230,
    sugar: 22,
    protein: 3.5,
    carbs: 28,
    fat: 13,
    commonPortions: [
      { name: '1 scoop', size: 66 },
      { name: '1/2 cup', size: 72 },
    ],
  },
  {
    id: 'ice-cream-butter-pecan',
    name: 'Butter Pecan Ice Cream',
    category: 'Ice Cream & Frozen',
    servingSize: 100,
    servingUnit: 'g',
    calories: 235,
    sugar: 20,
    protein: 3.2,
    carbs: 26,
    fat: 14,
    commonPortions: [
      { name: '1 scoop', size: 66 },
      { name: '1/2 cup', size: 72 },
    ],
  },
  {
    id: 'ice-cream-neapolitan',
    name: 'Neapolitan Ice Cream',
    category: 'Ice Cream & Frozen',
    servingSize: 100,
    servingUnit: 'g',
    calories: 205,
    sugar: 22,
    protein: 3.5,
    carbs: 25,
    fat: 11,
    commonPortions: [
      { name: '1 scoop', size: 66 },
      { name: '1/2 cup', size: 72 },
    ],
  },
  {
    id: 'frozen-yogurt',
    name: 'Frozen Yogurt (vanilla)',
    category: 'Ice Cream & Frozen',
    servingSize: 100,
    servingUnit: 'g',
    calories: 140,
    sugar: 18,
    protein: 4,
    carbs: 28,
    fat: 2,
    commonPortions: [
      { name: '1 scoop', size: 66 },
      { name: '1/2 cup', size: 72 },
    ],
  },
  {
    id: 'sorbet',
    name: 'Sorbet (fruit)',
    category: 'Ice Cream & Frozen',
    servingSize: 100,
    servingUnit: 'g',
    calories: 140,
    sugar: 28,
    protein: 0.5,
    carbs: 35,
    fat: 0,
    commonPortions: [
      { name: '1 scoop', size: 66 },
      { name: '1/2 cup', size: 72 },
    ],
  },
  {
    id: 'ice-cream-sandwich',
    name: 'Ice Cream Sandwich',
    category: 'Ice Cream & Frozen',
    servingSize: 100,
    servingUnit: 'g',
    calories: 237,
    sugar: 24,
    protein: 4,
    carbs: 38,
    fat: 8,
    commonPortions: [
      { name: '1 sandwich', size: 70 },
    ],
  },
  {
    id: 'ice-cream-bar-vanilla',
    name: 'Vanilla Ice Cream Bar',
    category: 'Ice Cream & Frozen',
    servingSize: 100,
    servingUnit: 'g',
    calories: 250,
    sugar: 22,
    protein: 3,
    carbs: 32,
    fat: 13,
    commonPortions: [
      { name: '1 bar', size: 60 },
    ],
  },
  {
    id: 'popsicle',
    name: 'Popsicle',
    category: 'Ice Cream & Frozen',
    servingSize: 100,
    servingUnit: 'g',
    calories: 76,
    sugar: 18,
    protein: 0,
    carbs: 19,
    fat: 0,
    commonPortions: [
      { name: '1 popsicle', size: 45 },
    ],
  },
  {
    id: 'frozen-birthday-cake',
    name: 'Frozen Birthday Cake',
    category: 'Ice Cream & Frozen',
    servingSize: 100,
    servingUnit: 'g',
    calories: 240,
    sugar: 25,
    protein: 3,
    carbs: 35,
    fat: 10,
    commonPortions: [
      { name: '1 slice', size: 80 },
      { name: '1 piece', size: 60 },
    ],
  },

  // Cakes & Pies
  {
    id: 'cake-chocolate',
    name: 'Chocolate Cake (with frosting)',
    category: 'Cakes & Pies',
    servingSize: 100,
    servingUnit: 'g',
    calories: 371,
    sugar: 38,
    protein: 4,
    carbs: 52,
    fat: 17,
    commonPortions: [
      { name: '1 slice', size: 80 },
      { name: '1 slice (large)', size: 120 },
    ],
  },
  {
    id: 'cake-vanilla',
    name: 'Vanilla Cake (with frosting)',
    category: 'Cakes & Pies',
    servingSize: 100,
    servingUnit: 'g',
    calories: 356,
    sugar: 40,
    protein: 4,
    carbs: 55,
    fat: 14,
    commonPortions: [
      { name: '1 slice', size: 80 },
      { name: '1 slice (large)', size: 120 },
    ],
  },
  {
    id: 'cake-red-velvet',
    name: 'Red Velvet Cake (with frosting)',
    category: 'Cakes & Pies',
    servingSize: 100,
    servingUnit: 'g',
    calories: 368,
    sugar: 42,
    protein: 4,
    carbs: 54,
    fat: 17,
    commonPortions: [
      { name: '1 slice', size: 80 },
    ],
  },
  {
    id: 'cake-carrot',
    name: 'Carrot Cake (with frosting)',
    category: 'Cakes & Pies',
    servingSize: 100,
    servingUnit: 'g',
    calories: 326,
    sugar: 32,
    protein: 4,
    carbs: 48,
    fat: 14,
    commonPortions: [
      { name: '1 slice', size: 90 },
    ],
  },
  {
    id: 'cake-cheesecake',
    name: 'Cheesecake (plain)',
    category: 'Cakes & Pies',
    servingSize: 100,
    servingUnit: 'g',
    calories: 321,
    sugar: 22,
    protein: 6,
    carbs: 26,
    fat: 23,
    commonPortions: [
      { name: '1 slice', size: 100 },
      { name: '1 slice (large)', size: 140 },
    ],
  },
  {
    id: 'cupcake',
    name: 'Cupcake (with frosting)',
    category: 'Cakes & Pies',
    servingSize: 100,
    servingUnit: 'g',
    calories: 378,
    sugar: 42,
    protein: 3,
    carbs: 55,
    fat: 17,
    commonPortions: [
      { name: '1 cupcake', size: 40 },
      { name: '1 large cupcake', size: 60 },
    ],
  },
  {
    id: 'brownie',
    name: 'Chocolate Brownie',
    category: 'Cakes & Pies',
    servingSize: 100,
    servingUnit: 'g',
    calories: 420,
    sugar: 35,
    protein: 5,
    carbs: 58,
    fat: 20,
    commonPortions: [
      { name: '1 brownie', size: 40 },
      { name: '1 large brownie', size: 60 },
    ],
  },
  {
    id: 'pie-apple',
    name: 'Apple Pie (with crust)',
    category: 'Cakes & Pies',
    servingSize: 100,
    servingUnit: 'g',
    calories: 237,
    sugar: 18,
    protein: 1.5,
    carbs: 34,
    fat: 11,
    commonPortions: [
      { name: '1 slice', size: 110 },
      { name: '1 slice (large)', size: 150 },
    ],
  },
  {
    id: 'pie-pumpkin',
    name: 'Pumpkin Pie (with crust)',
    category: 'Cakes & Pies',
    servingSize: 100,
    servingUnit: 'g',
    calories: 203,
    sugar: 14,
    protein: 4,
    carbs: 29,
    fat: 8,
    commonPortions: [
      { name: '1 slice', size: 110 },
    ],
  },
  {
    id: 'pie-pecan',
    name: 'Pecan Pie (with crust)',
    category: 'Cakes & Pies',
    servingSize: 100,
    servingUnit: 'g',
    calories: 408,
    sugar: 28,
    protein: 5,
    carbs: 47,
    fat: 22,
    commonPortions: [
      { name: '1 slice', size: 110 },
    ],
  },
  {
    id: 'pie-lemon-meringue',
    name: 'Lemon Meringue Pie',
    category: 'Cakes & Pies',
    servingSize: 100,
    servingUnit: 'g',
    calories: 233,
    sugar: 18,
    protein: 4,
    carbs: 35,
    fat: 9,
    commonPortions: [
      { name: '1 slice', size: 110 },
    ],
  },
  {
    id: 'cannoli',
    name: 'Cannoli',
    category: 'Cakes & Pies',
    servingSize: 100,
    servingUnit: 'g',
    calories: 219,
    sugar: 13,
    protein: 3,
    carbs: 24,
    fat: 11,
    commonPortions: [
      { name: '1 cannolo', size: 60 },
      { name: '1 large', size: 80 },
    ],
  },
  {
    id: 'cinnamon-roll',
    name: 'Cinnamon Roll (with frosting)',
    category: 'Cakes & Pies',
    servingSize: 100,
    servingUnit: 'g',
    calories: 390,
    sugar: 25,
    protein: 5,
    carbs: 55,
    fat: 16,
    commonPortions: [
      { name: '1 roll (small)', size: 55 },
      { name: '1 roll (large)', size: 100 },
    ],
  },
  {
    id: 'crepe',
    name: 'Crepes (plain)',
    category: 'Cakes & Pies',
    servingSize: 100,
    servingUnit: 'g',
    calories: 224,
    sugar: 7,
    protein: 6,
    carbs: 28,
    fat: 9,
    commonPortions: [
      { name: '1 crepe', size: 45 },
      { name: '2 crepes', size: 90 },
    ],
  },

  // Beverages
  {
    id: 'coffee-black',
    name: 'Black Coffee',
    category: 'Beverages',
    servingSize: 100,
    servingUnit: 'ml',
    calories: 1,
    sugar: 0,
    protein: 0.1,
    carbs: 0,
    fat: 0,
    commonPortions: [
      { name: '1 cup', size: 240 },
      { name: '1 mug', size: 350 },
    ],
  },
  {
    id: 'orange-juice',
    name: 'Orange Juice',
    category: 'Beverages',
    servingSize: 100,
    servingUnit: 'ml',
    calories: 45,
    sugar: 8.4,
    protein: 0.7,
    carbs: 10,
    fat: 0.2,
    commonPortions: [
      { name: '1 glass', size: 248 },
      { name: '1 small carton', size: 200 },
    ],
  },
  {
    id: 'soda-cola',
    name: 'Cola (Soda)',
    category: 'Beverages',
    servingSize: 100,
    servingUnit: 'ml',
    calories: 42,
    sugar: 10.6,
    protein: 0,
    carbs: 10.6,
    fat: 0,
    commonPortions: [
      { name: '1 can', size: 330 },
      { name: '1 bottle', size: 500 },
    ],
  },
  {
    id: 'water',
    name: 'Water',
    category: 'Beverages',
    servingSize: 100,
    servingUnit: 'ml',
    calories: 0,
    sugar: 0,
    protein: 0,
    carbs: 0,
    fat: 0,
    commonPortions: [
      { name: '1 glass', size: 240 },
      { name: '1 bottle', size: 500 },
    ],
  },

  // Fast Food
  {
    id: 'burger-mc',
    name: 'Hamburger (typical fast food)',
    category: 'Fast Food',
    servingSize: 1,
    servingUnit: 'burger',
    calories: 295,
    sugar: 7,
    protein: 17,
    carbs: 24,
    fat: 14,
    commonPortions: [
      { name: '1 burger', size: 1 },
    ],
  },
  {
    id: 'pizza-slice',
    name: 'Pizza Slice (cheese)',
    category: 'Fast Food',
    servingSize: 1,
    servingUnit: 'slice',
    calories: 272,
    sugar: 3.5,
    protein: 11,
    carbs: 33,
    fat: 10,
    commonPortions: [
      { name: '1 slice', size: 1 },
      { name: '2 slices', size: 2 },
    ],
  },
  {
    id: 'fries-medium',
    name: 'French Fries (medium)',
    category: 'Fast Food',
    servingSize: 1,
    servingUnit: 'serving',
    calories: 365,
    sugar: 0.3,
    protein: 4,
    carbs: 48,
    fat: 17,
    commonPortions: [
      { name: '1 serving', size: 1 },
      { name: '1 small', size: 0.7 },
    ],
  },
];

export const foodCategories = [
  'All',
  'Fruits',
  'Vegetables',
  'Proteins',
  'Grains & Starches',
  'Dairy',
  'Snacks & Sweets',
  'Ice Cream & Frozen',
  'Cakes & Pies',
  'Beverages',
  'Fast Food',
];

export const searchFoodDatabase = (query: string): FoodDatabaseItem[] => {
  const lowerQuery = query.toLowerCase();
  return foodDatabase.filter(
    (food) =>
      food.name.toLowerCase().includes(lowerQuery) ||
      food.category.toLowerCase().includes(lowerQuery)
  );
};

export const getFoodById = (id: string): FoodDatabaseItem | undefined => {
  return foodDatabase.find((food) => food.id === id);
};
