export interface FoodDatabaseItem {
  id: string;
  name: string;
  category: string;
  servingSize: number;
  servingUnit: string;
  calories: number;
  sugar: number;
  protein: number;
  carbs: number;
  fat: number;
  commonPortions: Array<{
    name: string;
    size: number;
  }>;
}

export const foodDatabase: FoodDatabaseItem[] = [
  // Fruits
  {
    id: 'apple',
    name: 'Apple',
    category: 'Fruits',
    servingSize: 100,
    servingUnit: 'g',
    calories: 52,
    sugar: 10.4,
    protein: 0.3,
    carbs: 14,
    fat: 0.2,
    commonPortions: [
      { name: '1 medium', size: 182 },
      { name: '1 small', size: 149 },
      { name: '1 cup sliced', size: 109 },
    ],
  },
  {
    id: 'banana',
    name: 'Banana',
    category: 'Fruits',
    servingSize: 100,
    servingUnit: 'g',
    calories: 89,
    sugar: 12.2,
    protein: 1.1,
    carbs: 23,
    fat: 0.3,
    commonPortions: [
      { name: '1 medium', size: 118 },
      { name: '1 small', size: 101 },
      { name: '1 cup sliced', size: 150 },
    ],
  },
  {
    id: 'orange',
    name: 'Orange',
    category: 'Fruits',
    servingSize: 100,
    servingUnit: 'g',
    calories: 47,
    sugar: 9.4,
    protein: 0.9,
    carbs: 12,
    fat: 0.1,
    commonPortions: [
      { name: '1 medium', size: 131 },
      { name: '1 small', size: 96 },
    ],
  },
  {
    id: 'grapes',
    name: 'Grapes',
    category: 'Fruits',
    servingSize: 100,
    servingUnit: 'g',
    calories: 69,
    sugar: 15.5,
    protein: 0.7,
    carbs: 18,
    fat: 0.2,
    commonPortions: [
      { name: '1 cup', size: 151 },
      { name: '1 bunch', size: 250 },
    ],
  },
  {
    id: 'strawberries',
    name: 'Strawberries',
    category: 'Fruits',
    servingSize: 100,
    servingUnit: 'g',
    calories: 32,
    sugar: 4.9,
    protein: 0.7,
    carbs: 7.7,
    fat: 0.3,
    commonPortions: [
      { name: '1 cup whole', size: 152 },
      { name: '1 cup sliced', size: 166 },
    ],
  },
  {
    id: 'blueberries',
    name: 'Blueberries',
    category: 'Fruits',
    servingSize: 100,
    servingUnit: 'g',
    calories: 57,
    sugar: 10,
    protein: 0.7,
    carbs: 14,
    fat: 0.3,
    commonPortions: [
      { name: '1 cup', size: 148 },
    ],
  },
  {
    id: 'watermelon',
    name: 'Watermelon',
    category: 'Fruits',
    servingSize: 100,
    servingUnit: 'g',
    calories: 30,
    sugar: 6.2,
    protein: 0.6,
    carbs: 8,
    fat: 0.2,
    commonPortions: [
      { name: '1 cup diced', size: 152 },
      { name: '1 wedge', size: 286 },
    ],
  },

  // Vegetables
  {
    id: 'broccoli',
    name: 'Broccoli',
    category: 'Vegetables',
    servingSize: 100,
    servingUnit: 'g',
    calories: 34,
    sugar: 1.7,
    protein: 2.8,
    carbs: 7,
    fat: 0.4,
    commonPortions: [
      { name: '1 cup chopped', size: 91 },
      { name: '1 stalk', size: 151 },
    ],
  },
  {
    id: 'carrot',
    name: 'Carrot',
    category: 'Vegetables',
    servingSize: 100,
    servingUnit: 'g',
    calories: 41,
    sugar: 4.7,
    protein: 0.9,
    carbs: 10,
    fat: 0.2,
    commonPortions: [
      { name: '1 medium', size: 61 },
      { name: '1 cup chopped', size: 128 },
    ],
  },
  {
    id: 'spinach',
    name: 'Spinach',
    category: 'Vegetables',
    servingSize: 100,
    servingUnit: 'g',
    calories: 23,
    sugar: 0.4,
    protein: 2.9,
    carbs: 3.6,
    fat: 0.4,
    commonPortions: [
      { name: '1 cup raw', size: 30 },
      { name: '1 cup cooked', size: 180 },
    ],
  },
  {
    id: 'tomato',
    name: 'Tomato',
    category: 'Vegetables',
    servingSize: 100,
    servingUnit: 'g',
    calories: 18,
    sugar: 2.6,
    protein: 0.9,
    carbs: 3.9,
    fat: 0.2,
    commonPortions: [
      { name: '1 medium', size: 123 },
      { name: '1 cup chopped', size: 180 },
    ],
  },
  {
    id: 'potato',
    name: 'Potato',
    category: 'Vegetables',
    servingSize: 100,
    servingUnit: 'g',
    calories: 77,
    sugar: 0.8,
    protein: 2,
    carbs: 17,
    fat: 0.1,
    commonPortions: [
      { name: '1 medium', size: 213 },
      { name: '1 cup diced', size: 132 },
    ],
  },

  // Proteins
  {
    id: 'chicken-breast',
    name: 'Chicken Breast',
    category: 'Proteins',
    servingSize: 100,
    servingUnit: 'g',
    calories: 165,
    sugar: 0,
    protein: 31,
    carbs: 0,
    fat: 3.6,
    commonPortions: [
      { name: '1 breast', size: 172 },
      { name: '1 cup diced', size: 140 },
    ],
  },
  {
    id: 'salmon',
    name: 'Salmon',
    category: 'Proteins',
    servingSize: 100,
    servingUnit: 'g',
    calories: 208,
    sugar: 0,
    protein: 20,
    carbs: 0,
    fat: 13,
    commonPortions: [
      { name: '1 fillet (half)', size: 178 },
      { name: '1 cup cooked', size: 154 },
    ],
  },
  {
    id: 'egg',
    name: 'Egg',
    category: 'Proteins',
    servingSize: 100,
    servingUnit: 'g',
    calories: 155,
    sugar: 1.1,
    protein: 13,
    carbs: 1.1,
    fat: 11,
    commonPortions: [
      { name: '1 large', size: 50 },
      { name: '1 extra large', size: 56 },
    ],
  },
  {
    id: 'beef-ground',
    name: 'Ground Beef (85%)',
    category: 'Proteins',
    servingSize: 100,
    servingUnit: 'g',
    calories: 250,
    sugar: 0,
    protein: 26,
    carbs: 0,
    fat: 17,
    commonPortions: [
      { name: '1 patty', size: 113 },
      { name: '1 cup cooked', size: 226 },
    ],
  },
  {
    id: 'tofu',
    name: 'Tofu',
    category: 'Proteins',
    servingSize: 100,
    servingUnit: 'g',
    calories: 76,
    sugar: 0.9,
    protein: 8,
    carbs: 1.9,
    fat: 4.8,
    commonPortions: [
      { name: '1 cup cubed', size: 126 },
    ],
  },

  // Grains & Starches
  {
    id: 'rice-white',
    name: 'White Rice (cooked)',
    category: 'Grains & Starches',
    servingSize: 100,
    servingUnit: 'g',
    calories: 130,
    sugar: 0.1,
    protein: 2.7,
    carbs: 28,
    fat: 0.3,
    commonPortions: [
      { name: '1 cup', size: 158 },
      { name: '1 bowl', size: 200 },
    ],
  },
  {
    id: 'rice-brown',
    name: 'Brown Rice (cooked)',
    category: 'Grains & Starches',
    servingSize: 100,
    servingUnit: 'g',
    calories: 112,
    sugar: 0.4,
    protein: 2.6,
    carbs: 24,
    fat: 0.9,
    commonPortions: [
      { name: '1 cup', size: 195 },
      { name: '1 bowl', size: 200 },
    ],
  },
  {
    id: 'bread-white',
    name: 'White Bread',
    category: 'Grains & Starches',
    servingSize: 100,
    servingUnit: 'g',
    calories: 265,
    sugar: 5,
    protein: 9,
    carbs: 49,
    fat: 3.2,
    commonPortions: [
      { name: '1 slice', size: 25 },
      { name: '2 slices', size: 50 },
    ],
  },
  {
    id: 'bread-whole',
    name: 'Whole Wheat Bread',
    category: 'Grains & Starches',
    servingSize: 100,
    servingUnit: 'g',
    calories: 247,
    sugar: 5.5,
    protein: 13,
    carbs: 41,
    fat: 3.4,
    commonPortions: [
      { name: '1 slice', size: 28 },
      { name: '2 slices', size: 56 },
    ],
  },
  {
    id: 'pasta',
    name: 'Pasta (cooked)',
    category: 'Grains & Starches',
    servingSize: 100,
    servingUnit: 'g',
    calories: 131,
    sugar: 1.3,
    protein: 5,
    carbs: 25,
    fat: 1.1,
    commonPortions: [
      { name: '1 cup', size: 140 },
      { name: '1 bowl', size: 220 },
    ],
  },
  {
    id: 'oatmeal',
    name: 'Oatmeal (cooked)',
    category: 'Grains & Starches',
    servingSize: 100,
    servingUnit: 'g',
    calories: 71,
    sugar: 0.6,
    protein: 2.5,
    carbs: 12,
    fat: 1.4,
    commonPortions: [
      { name: '1 cup', size: 234 },
      { name: '1 bowl', size: 250 },
    ],
  },

  // Dairy
  {
    id: 'milk-whole',
    name: 'Whole Milk',
    category: 'Dairy',
    servingSize: 100,
    servingUnit: 'ml',
    calories: 61,
    sugar: 5,
    protein: 3.2,
    carbs: 4.8,
    fat: 3.3,
    commonPortions: [
      { name: '1 cup', size: 244 },
      { name: '1 glass', size: 300 },
    ],
  },
  {
    id: 'milk-skim',
    name: 'Skim Milk',
    category: 'Dairy',
    servingSize: 100,
    servingUnit: 'ml',
    calories: 34,
    sugar: 5,
    protein: 3.4,
    carbs: 5,
    fat: 0.1,
    commonPortions: [
      { name: '1 cup', size: 244 },
      { name: '1 glass', size: 300 },
    ],
  },
  {
    id: 'yogurt-greek',
    name: 'Greek Yogurt',
    category: 'Dairy',
    servingSize: 100,
    servingUnit: 'g',
    calories: 59,
    sugar: 3.6,
    protein: 10,
    carbs: 3.6,
    fat: 0.4,
    commonPortions: [
      { name: '1 cup', size: 245 },
      { name: '1 container', size: 170 },
    ],
  },
  {
    id: 'cheese-cheddar',
    name: 'Cheddar Cheese',
    category: 'Dairy',
    servingSize: 100,
    servingUnit: 'g',
    calories: 403,
    sugar: 0.5,
    protein: 25,
    carbs: 1.3,
    fat: 33,
    commonPortions: [
      { name: '1 oz', size: 28 },
      { name: '1 cup shredded', size: 113 },
    ],
  },

  // Snacks & Sweets
  {
    id: 'almonds',
    name: 'Almonds',
    category: 'Snacks & Sweets',
    servingSize: 100,
    servingUnit: 'g',
    calories: 579,
    sugar: 4,
    protein: 21,
    carbs: 22,
    fat: 50,
    commonPortions: [
      { name: '1 handful', size: 23 },
      { name: '1/4 cup', size: 30 },
    ],
  },
  {
    id: 'peanut-butter',
    name: 'Peanut Butter',
    category: 'Snacks & Sweets',
    servingSize: 100,
    servingUnit: 'g',
    calories: 588,
    sugar: 9,
    protein: 25,
    carbs: 20,
    fat: 50,
    commonPortions: [
      { name: '1 tbsp', size: 16 },
      { name: '2 tbsp', size: 32 },
    ],
  },
  {
    id: 'dark-chocolate',
    name: 'Dark Chocolate (70%)',
    category: 'Snacks & Sweets',
    servingSize: 100,
    servingUnit: 'g',
    calories: 598,
    sugar: 24,
    protein: 7.8,
    carbs: 46,
    fat: 43,
    commonPortions: [
      { name: '1 square', size: 10 },
      { name: '1 bar', size: 40 },
    ],
  },
  {
    id: 'chips-potato',
    name: 'Potato Chips',
    category: 'Snacks & Sweets',
    servingSize: 100,
    servingUnit: 'g',
    calories: 536,
    sugar: 0.4,
    protein: 7,
    carbs: 53,
    fat: 35,
    commonPortions: [
      { name: '1 small bag', size: 28 },
      { name: '1 handful', size: 20 },
    ],
  },

  // Beverages
  {
    id: 'coffee-black',
    name: 'Black Coffee',
    category: 'Beverages',
    servingSize: 100,
    servingUnit: 'ml',
    calories: 1,
    sugar: 0,
    protein: 0.1,
    carbs: 0,
    fat: 0,
    commonPortions: [
      { name: '1 cup', size: 240 },
      { name: '1 mug', size: 350 },
    ],
  },
  {
    id: 'orange-juice',
    name: 'Orange Juice',
    category: 'Beverages',
    servingSize: 100,
    servingUnit: 'ml',
    calories: 45,
    sugar: 8.4,
    protein: 0.7,
    carbs: 10,
    fat: 0.2,
    commonPortions: [
      { name: '1 glass', size: 248 },
      { name: '1 small carton', size: 200 },
    ],
  },
  {
    id: 'soda-cola',
    name: 'Cola (Soda)',
    category: 'Beverages',
    servingSize: 100,
    servingUnit: 'ml',
    calories: 42,
    sugar: 10.6,
    protein: 0,
    carbs: 10.6,
    fat: 0,
    commonPortions: [
      { name: '1 can', size: 330 },
      { name: '1 bottle', size: 500 },
    ],
  },
  {
    id: 'water',
    name: 'Water',
    category: 'Beverages',
    servingSize: 100,
    servingUnit: 'ml',
    calories: 0,
    sugar: 0,
    protein: 0,
    carbs: 0,
    fat: 0,
    commonPortions: [
      { name: '1 glass', size: 240 },
      { name: '1 bottle', size: 500 },
    ],
  },

  // Fast Food
  {
    id: 'burger-mc',
    name: 'Hamburger (typical fast food)',
    category: 'Fast Food',
    servingSize: 1,
    servingUnit: 'burger',
    calories: 295,
    sugar: 7,
    protein: 17,
    carbs: 24,
    fat: 14,
    commonPortions: [
      { name: '1 burger', size: 1 },
    ],
  },
  {
    id: 'pizza-slice',
    name: 'Pizza Slice (cheese)',
    category: 'Fast Food',
    servingSize: 1,
    servingUnit: 'slice',
    calories: 272,
    sugar: 3.5,
    protein: 11,
    carbs: 33,
    fat: 10,
    commonPortions: [
      { name: '1 slice', size: 1 },
      { name: '2 slices', size: 2 },
    ],
  },
  {
    id: 'fries-medium',
    name: 'French Fries (medium)',
    category: 'Fast Food',
    servingSize: 1,
    servingUnit: 'serving',
    calories: 365,
    sugar: 0.3,
    protein: 4,
    carbs: 48,
    fat: 17,
    commonPortions: [
      { name: '1 serving', size: 1 },
      { name: '1 small', size: 0.7 },
    ],
  },
];

export const foodCategories = [
  'All',
  'Fruits',
  'Vegetables',
  'Proteins',
  'Grains & Starches',
  'Dairy',
  'Snacks & Sweets',
  'Beverages',
  'Fast Food',
];

export const searchFoodDatabase = (query: string): FoodDatabaseItem[] => {
  const lowerQuery = query.toLowerCase();
  return foodDatabase.filter(
    (food) =>
      food.name.toLowerCase().includes(lowerQuery) ||
      food.category.toLowerCase().includes(lowerQuery)
  );
};

export const getFoodById = (id: string): FoodDatabaseItem | undefined => {
  return foodDatabase.find((food) => food.id === id);
};
